-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."asociacionInfracciones"
(
    "catalogoInfraccion" integer NOT NULL,
    folio uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public."catalogoInfracciones"
(
    "idCatalogo" serial NOT NULL,
    "infraccionCometida" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "fundamentoLegal" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uma double precision,
    CONSTRAINT "catalogoInfracciones_pkey" PRIMARY KEY ("idCatalogo")
);

CREATE TABLE IF NOT EXISTS public."folioInfracciones"
(
    folio uuid NOT NULL,
    "idOficial" uuid,
    infraccion uuid,
    CONSTRAINT "folioInfracciones_pkey" PRIMARY KEY (folio)
);

CREATE TABLE IF NOT EXISTS public.infracciones
(
    "idInfraccion" uuid NOT NULL,
    version smallint NOT NULL DEFAULT 0,
    "folioInfraccion" uuid NOT NULL,
    "lineaCaptura" uuid,
    fecha timestamp with time zone NOT NULL DEFAULT now(),
    ubicacion uuid NOT NULL,
    conductor character varying(13) COLLATE pg_catalog."default" NOT NULL,
    "emisorInfraccion" character varying(13) COLLATE pg_catalog."default" NOT NULL,
    "vehiculoInfraccionado" character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT infracciones_pkey PRIMARY KEY ("idInfraccion")
);

CREATE TABLE IF NOT EXISTS public.ubicacion
(
    id uuid NOT NULL,
    municipio character varying(255) COLLATE pg_catalog."default",
    colonia character varying(255) COLLATE pg_catalog."default",
    calle character varying(255) COLLATE pg_catalog."default",
    numero integer,
    tramo character varying(255) COLLATE pg_catalog."default",
    ruta character varying(255) COLLATE pg_catalog."default",
    kilometro double precision,
    clasificacioncarretera character varying(255) COLLATE pg_catalog."default",
    manzanas double precision,
    lotes double precision,
    location geography(Point,4326),
    CONSTRAINT ubicacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.depositos
(
    "idDeposito" uuid NOT NULL,
    "idUbicacion" uuid NOT NULL,
    "capacidadMaxima" integer NOT NULL,
    CONSTRAINT depositos_pkey PRIMARY KEY ("idDeposito")
);

CREATE TABLE IF NOT EXISTS public."registroDeposito"
(
    "idRegistro" uuid NOT NULL,
    "idDeposito" uuid NOT NULL,
    folio uuid NOT NULL,
    "placaVehiculo" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "rfcPropietario" character varying(13) COLLATE pg_catalog."default" NOT NULL,
    "fechaIngreso" timestamp with time zone NOT NULL,
    "fechaEgreso" timestamp with time zone,
    CONSTRAINT "registroDeposito_pkey" PRIMARY KEY ("idRegistro")
);

CREATE TABLE IF NOT EXISTS public.gruas
(
    "idGrua" uuid NOT NULL,
    "idUbicacion" uuid NOT NULL,
    ocupado boolean NOT NULL,
    CONSTRAINT gruas_pkey PRIMARY KEY ("idGrua")
);

CREATE TABLE IF NOT EXISTS public."registroArrastre"
(
    "idRegistro" uuid NOT NULL,
    folio uuid NOT NULL,
    fecha timestamp with time zone NOT NULL,
    "ubicacionInicial" uuid NOT NULL,
    "ubicacionFinal" uuid NOT NULL,
    CONSTRAINT "registroArrastre_pkey" PRIMARY KEY ("idRegistro")
);

CREATE TABLE IF NOT EXISTS public."asociacionEvidenciaArrastre"
(
    "idEvidenciaArrstre" uuid NOT NULL,
    "idRegistroArrastre" uuid NOT NULL,
    CONSTRAINT "asociacionEvidenciaArrastre_pkey" PRIMARY KEY ("idEvidenciaArrstre", "idRegistroArrastre")
);

CREATE TABLE IF NOT EXISTS public."evidenciaArrastre"
(
    "idEvideciaArrastre" uuid NOT NULL,
    "idEvidencia" uuid NOT NULL,
    "personalGrua" uuid NOT NULL,
    CONSTRAINT "evidenciaArrastre_pkey" PRIMARY KEY ("idEvideciaArrastre")
);

CREATE TABLE IF NOT EXISTS public.evidencias
(
    "idEvicencia" uuid NOT NULL,
    imagen bit(1),
    CONSTRAINT evidencias_pkey PRIMARY KEY ("idEvicencia")
);

CREATE TABLE IF NOT EXISTS public."asociacionEvidenciasInfracciones"
(
    evidencia uuid NOT NULL,
    folio uuid NOT NULL,
    CONSTRAINT "llavePrimaria" PRIMARY KEY (evidencia, folio)
);

CREATE TABLE IF NOT EXISTS public.personal
(
    "idPersona" uuid NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "primerApellido" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "segundoApellido" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rfc character varying(13) COLLATE pg_catalog."default" NOT NULL,
    "numeroLicenca" bigint NOT NULL,
    cargo character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "idPersonal" PRIMARY KEY ("idPersona")
);

CREATE TABLE IF NOT EXISTS public.credencial
(
    "numeroCredencial" bigint NOT NULL,
    "fechaExpedicion" timestamp with time zone NOT NULL,
    "fechaExpiracion" timestamp with time zone NOT NULL,
    autoridad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    emisor uuid NOT NULL,
    CONSTRAINT credencial_pkey PRIMARY KEY ("numeroCredencial")
);

CREATE TABLE IF NOT EXISTS public.vehiculo
(
    placa character varying(15) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    marca character varying(100) COLLATE pg_catalog."default" NOT NULL,
    serie character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT vehiculo_pkey PRIMARY KEY (placa)
);

CREATE TABLE IF NOT EXISTS public."datosVehiculoComercial"
(
    "idDatosVehiculo" uuid NOT NULL,
    remolque1 character varying(15) COLLATE pg_catalog."default",
    remolque2 character varying(15) COLLATE pg_catalog."default",
    convertidor character varying(15) COLLATE pg_catalog."default",
    propietario character varying(13) COLLATE pg_catalog."default" NOT NULL,
    "cargaTransportada" character varying(255) COLLATE pg_catalog."default",
    folio uuid NOT NULL,
    CONSTRAINT "datosVehiculoComercial_pkey" PRIMARY KEY ("idDatosVehiculo")
);

CREATE TABLE IF NOT EXISTS public."excesoDimension"
(
    "idExcesoDim" uuid NOT NULL,
    "largoVehiculo" real NOT NULL,
    "anchoVehiculo" real NOT NULL,
    "altoVehiculo" real NOT NULL,
    "largoAutorizado" real NOT NULL,
    "anchoAutorizado" real NOT NULL,
    "altoAutorizado" real NOT NULL,
    folio uuid,
    CONSTRAINT "excesoDimension_pkey" PRIMARY KEY ("idExcesoDim")
);

CREATE TABLE IF NOT EXISTS public."excesoPeso"
(
    "idExcesoPeso" uuid NOT NULL,
    folio uuid NOT NULL,
    ejes smallint[] NOT NULL
);

ALTER TABLE IF EXISTS public."asociacionInfracciones"
    ADD CONSTRAINT catalogo FOREIGN KEY ("catalogoInfraccion")
    REFERENCES public."catalogoInfracciones" ("idCatalogo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."asociacionInfracciones"
    ADD CONSTRAINT folio FOREIGN KEY (folio)
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.infracciones
    ADD CONSTRAINT folio FOREIGN KEY ("folioInfraccion")
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_folio
    ON public.infracciones("folioInfraccion");


ALTER TABLE IF EXISTS public.infracciones
    ADD CONSTRAINT ubicacionkey FOREIGN KEY (ubicacion)
    REFERENCES public.ubicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.infracciones
    ADD CONSTRAINT vehiculo FOREIGN KEY ("vehiculoInfraccionado")
    REFERENCES public.vehiculo (placa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_vehiculo
    ON public.infracciones("vehiculoInfraccionado");


ALTER TABLE IF EXISTS public.depositos
    ADD CONSTRAINT ubicacion FOREIGN KEY ("idUbicacion")
    REFERENCES public.ubicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."registroDeposito"
    ADD CONSTRAINT folio FOREIGN KEY (folio)
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."registroDeposito"
    ADD CONSTRAINT "registroDeposito_idDeposito_fkey" FOREIGN KEY ("idDeposito")
    REFERENCES public.depositos ("idDeposito") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.gruas
    ADD CONSTRAINT ubicacion FOREIGN KEY ("idUbicacion")
    REFERENCES public.ubicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."registroArrastre"
    ADD CONSTRAINT folio FOREIGN KEY (folio)
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."registroArrastre"
    ADD CONSTRAINT ubicacion FOREIGN KEY ("ubicacionInicial")
    REFERENCES public.ubicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."registroArrastre"
    ADD CONSTRAINT "ubicacionFinal" FOREIGN KEY ("ubicacionFinal")
    REFERENCES public.ubicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."asociacionEvidenciaArrastre"
    ADD CONSTRAINT evidencia FOREIGN KEY ("idEvidenciaArrstre")
    REFERENCES public."evidenciaArrastre" ("idEvideciaArrastre") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."asociacionEvidenciaArrastre"
    ADD CONSTRAINT registro FOREIGN KEY ("idRegistroArrastre")
    REFERENCES public."registroArrastre" ("idRegistro") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."evidenciaArrastre"
    ADD CONSTRAINT evidencia FOREIGN KEY ("idEvidencia")
    REFERENCES public.evidencias ("idEvicencia") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."evidenciaArrastre"
    ADD CONSTRAINT personal FOREIGN KEY ("personalGrua")
    REFERENCES public.personal ("idPersona") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."asociacionEvidenciasInfracciones"
    ADD CONSTRAINT evidencia FOREIGN KEY (evidencia)
    REFERENCES public.evidencias ("idEvicencia") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."asociacionEvidenciasInfracciones"
    ADD CONSTRAINT folio FOREIGN KEY (folio)
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.credencial
    ADD CONSTRAINT emisor FOREIGN KEY (emisor)
    REFERENCES public.personal ("idPersona") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."datosVehiculoComercial"
    ADD CONSTRAINT convertidor FOREIGN KEY (convertidor)
    REFERENCES public.vehiculo (placa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."datosVehiculoComercial"
    ADD CONSTRAINT remolque1 FOREIGN KEY (remolque1)
    REFERENCES public.vehiculo (placa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."datosVehiculoComercial"
    ADD CONSTRAINT remolque2 FOREIGN KEY (remolque2)
    REFERENCES public.vehiculo (placa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."excesoDimension"
    ADD CONSTRAINT folio FOREIGN KEY (folio)
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."excesoPeso"
    ADD CONSTRAINT folio FOREIGN KEY (folio)
    REFERENCES public."folioInfracciones" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;